project_id = "rggohnwmajmrvxgfmimk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[storage]
enabled = true
port = 54327

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://ad75c518-0b07-43a9-ab8c-a632301b859c.lovableproject.com"]
jwt_expiry = 3600

[edge_functions]
enabled = true
port = 54329

[functions.ai-coach]
verify_jwt = true

[functions.music-ai-recommendations]
verify_jwt = true

[functions.video-ai-recommendations] 
verify_jwt = true